name: Build Evaluation Function Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: lambda-feedback/evaluation-function-workflows/.github/workflows/build.yml@main
    with:
      build-target: final
    permissions:
      contents: read
      id-token: write
      packages: write
