name: Deploy to Lambda Feedback

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    uses: lambda-feedback/evaluation-function-workflows/.github/workflows/deploy.yml@main
    with:
      template-repository-name: 'lambda-feedback/evaluation-function-boilerplate-wolfram'
      build-platforms: 'gcp'
    secrets:
      function-admin-api-key: ${{ secrets.FUNCTION_ADMIN_API_KEY}}
      gcp_credentials: ${{ secrets.gcp_credentials }}
